---
kind: pipeline
name: compliance

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    pull: always
    image: golang:1.14
    commands:
      - make fmt-check
      - make misspell-check
      - make lint

  - name: test
    pull: always
    image: golang:1.14
    commands:
      - make test
    depends_on:
      - lint

  - name: coverage
    pull: always
    image: robertstettner/drone-codecov
    settings:
      files:
        - coverage.out
    environment:
      CODECOV_TOKEN:
        from_secret: codecov_token
    depends_on:
      - test
    when:
      branch:
        - master
      event:
        - push
        - pull_request
